services:
    # Different servers because replicas do not work well with nginx
    express-1:
        build: server
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - frontend-network
            - backend-network
        volumes:
            - ./server/src:/app/src
        depends_on:
            - redis
        environment:
            - PORT=3000
            - REDIS_HOST=redis-container
            - SERVER_NAME=express-1
    express-2:
        build: server
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - frontend-network
            - backend-network
        volumes:
            - ./server/src:/app/src
        depends_on:
            - redis
        environment:
            - PORT=3000
            - REDIS_HOST=redis-container
            - SERVER_NAME=express-2
    flask-1:
        build: python-server
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - frontend-network
            - backend-network
        volumes:
            - ./python-server/src:/python-docker/src
        depends_on:
            - redis
        environment:
            - PORT=3000
            - REDIS_HOST=redis-container
            - SERVER_NAME=flask-1
    flask-2:
        build: python-server
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - frontend-network
            - backend-network
        volumes:
            - ./python-server/src:/python-docker/src
        depends_on:
            - redis
        environment:
            - PORT=3000
            - REDIS_HOST=redis-container
            - SERVER_NAME=flask-2
    nginx:
        container_name: nginx-container
        build: proxy
        ports:
            - '8080:80'
        networks:
            - frontend-network
        depends_on:
            - express-1
            - express-2
            - flask-1
            - flask-2
        volumes:
            - ./client/build:/usr/share/nginx/html
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    redis:
        container_name: redis-container
        image: redis
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - backend-network
        volumes:
            - ./database/data:/data
networks:
    frontend-network:
        driver: bridge
    backend-network:
        driver: bridge
