FROM python:3.10-alpine

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "--app", "./src/main.py", "run", "--host=0.0.0.0", "--port=3000"]